# Generated by Django 4.2.7 on 2025-08-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='External image URL (e.g., Google Drive link)', null=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (e.g., Google Drive link)', null=True),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/gallery/'),
        ),
    ]
